import java.util.Scanner;

public class SeasonsSwitch {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		Scanner scanner = new Scanner(System.in);
		String input;
		System.out.print("Please enter the date: ");
		input = scanner.next();
		int number = scanner.nextInt();
		
		switch(input.toLowerCase()) {
	
		case("march"):
			switch(number) {
			case 1:System.out.println("It's Winter!");
				break;
			case 2:System.out.println("It's Winter!");
				break;
			case 3:System.out.println("It's Winter!");
				break;
			case 4:System.out.println("It's Winter!");
				break;
			case 5:System.out.println("It's Winter!");
				break;
			case 6:System.out.println("It's Winter!");
				break;
			case 7:System.out.println("It's Winter!");
				break;
			case 8:System.out.println("It's Winter!");
				break;
			case 9:System.out.println("It's Winter!");
				break;
			case 10:System.out.println("It's Winter!");
				break;
			case 11:System.out.println("It's Winter!");
				break;
			case 12:System.out.println("It's Winter!");
				break;
			case 13:System.out.println("It's Winter!");
				break;
			case 14:System.out.println("It's Winter!");
				break;
			case 15:System.out.println("It's Winter!");
				break;
			case 16:System.out.println("It's Winter!");
				break;
			case 17:System.out.println("It's Winter!");
				break;
			case 18:System.out.println("It's Winter!");
				break;
			case 19:System.out.println("It's Winter!");
				break;
			case 20:System.out.println("It's Spring!");
				break;
			case 21:System.out.println("It's Spring!");
				break;
			case 22:System.out.println("It's Spring!");
				break;
			case 23:System.out.println("It's Spring!");
				break;
			case 24:System.out.println("It's Spring!");
				break;
			case 25:System.out.println("It's Spring!");
				break;
			case 26:System.out.println("It's Spring!");
				break;
			case 27:System.out.println("It's Spring!");
				break;
			case 28:System.out.println("It's Spring!");
				break;
			case 29:System.out.println("It's Spring!");
				break;
			case 30:System.out.println("It's Spring!");
				break;
			case 31:System.out.println("It's Spring!");
			break;
			default:System.out.println("Invaild date");
			break;
			}
		break;
		
		case("april"):switch(number) {
		case 1:System.out.println("It's Spring!");
		break;
	case 2:System.out.println("It's Spring!");
		break;
	case 3:System.out.println("It's Spring!");
		break;
	case 4:System.out.println("It's Spring!");
		break;
	case 5:System.out.println("It's Spring!");
		break;
	case 6:System.out.println("It's Spring!");
		break;
	case 7:System.out.println("It's Spring!");
		break;
	case 8:System.out.println("It's Spring!");
		break;
	case 9:System.out.println("It's Spring!");
		break;
	case 10:System.out.println("It's Spring!");
		break;
	case 11:System.out.println("It's Spring!");
		break;
	case 12:System.out.println("It's Spring!");
		break;
	case 13:System.out.println("It's Spring!");
		break;
	case 14:System.out.println("It's Spring!");
		break;
	case 15:System.out.println("It's Spring!");
		break;
	case 16:System.out.println("It's Spring!");
		break;
	case 17:System.out.println("It's Spring!");
		break;
	case 18:System.out.println("It's Spring!");
		break;
	case 19:System.out.println("It's Spring!");
		break;
	case 20:System.out.println("It's Spring!");
		break;
	case 21:System.out.println("It's Spring!");
		break;
	case 22:System.out.println("It's Spring!");
		break;
	case 23:System.out.println("It's Spring!");
		break;
	case 24:System.out.println("It's Spring!");
		break;
	case 25:System.out.println("It's Spring!");
		break;
	case 26:System.out.println("It's Spring!");
		break;
	case 27:System.out.println("It's Spring!");
		break;
	case 28:System.out.println("It's Spring!");
		break;
	case 29:System.out.println("It's Spring!");
		break;
	case 30:System.out.println("It's Spring!");
		break;
	default:System.out.println("Invaild date");
	break;
	}		
		break;
		case("may"):
			switch(number) {
			case 1:System.out.println("It's Spring!");
			break;
		case 2:System.out.println("It's Spring!");
			break;
		case 3:System.out.println("It's Spring!");
			break;
		case 4:System.out.println("It's Spring!");
			break;
		case 5:System.out.println("It's Spring!");
			break;
		case 6:System.out.println("It's Spring!");
			break;
		case 7:System.out.println("It's Spring!");
			break;
		case 8:System.out.println("It's Spring!");
			break;
		case 9:System.out.println("It's Spring!");
			break;
		case 10:System.out.println("It's Spring!");
			break;
		case 11:System.out.println("It's Spring!");
			break;
		case 12:System.out.println("It's Spring!");
			break;
		case 13:System.out.println("It's Spring!");
			break;
		case 14:System.out.println("It's Spring!");
			break;
		case 15:System.out.println("It's Spring!");
			break;
		case 16:System.out.println("It's Spring!");
			break;
		case 17:System.out.println("It's Spring!");
			break;
		case 18:System.out.println("It's Spring!");
			break;
		case 19:System.out.println("It's Spring!");
			break;
		case 20:System.out.println("It's Spring!");
			break;
		case 21:System.out.println("It's Spring!");
			break;
		case 22:System.out.println("It's Spring!");
			break;
		case 23:System.out.println("It's Spring!");
			break;
		case 24:System.out.println("It's Spring!");
			break;
		case 25:System.out.println("It's Spring!");
			break;
		case 26:System.out.println("It's Spring!");
			break;
		case 27:System.out.println("It's Spring!");
			break;
		case 28:System.out.println("It's Spring!");
			break;
		case 29:System.out.println("It's Spring!");
			break;
		case 30:System.out.println("It's Spring!");
			break;
		default:System.out.println("Invaild date");
		break;
		}
		break;
		case("june"):
			switch(number) {
			case 1:System.out.println("It's Spring!");
			break;
		case 2:System.out.println("It's Spring!");
			break;
		case 3:System.out.println("It's Spring!");
			break;
		case 4:System.out.println("It's Spring!");
			break;
		case 5:System.out.println("It's Spring!");
			break;
		case 6:System.out.println("It's Spring!");
			break;
		case 7:System.out.println("It's Spring!");
			break;
		case 8:System.out.println("It's Spring!");
			break;
		case 9:System.out.println("It's Spring!");
			break;
		case 10:System.out.println("It's Spring!");
			break;
		case 11:System.out.println("It's Spring!");
			break;
		case 12:System.out.println("It's Spring!");
			break;
		case 13:System.out.println("It's Spring!");
			break;
		case 14:System.out.println("It's Spring!");
			break;
		case 15:System.out.println("It's Spring!");
			break;
		case 16:System.out.println("It's Spring!");
			break;
		case 17:System.out.println("It's Spring!");
			break;
		case 18:System.out.println("It's Spring!");
			break;
		case 19:System.out.println("It's Spring!");
			break;
		case 20:System.out.println("It's Spring!");
			break;
		case 21:System.out.println("It's Summer!");
			break;
		case 22:System.out.println("It's Summer!");
			break;
		case 23:System.out.println("It's Summer!");
			break;
		case 24:System.out.println("It's Summer!");
			break;
		case 25:System.out.println("It's Summer!");
			break;
		case 26:System.out.println("It's Summer!");
			break;
		case 27:System.out.println("It's Summer!");
			break;
		case 28:System.out.println("It's Summer!");
			break;
		case 29:System.out.println("It's Summer!");
			break;
		case 30:System.out.println("It's Summer!");
			break;
		case 31:System.out.println("It's Summer!");
		break;
		default:System.out.println("Invaild date");
		break;
		}
		break;
		
		default:System.out.println("Invaild Date");
		break;
	}

}
}
